<?php

/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2018/6/6
 * Time: 下午4:11
 */

namespace app\common\models;

use app\common\exceptions\AppException;
use app\common\traits\BelongsStatusTrait;
use app\common\traits\HasProcessTrait;
use app\common\traits\CanPendingTrait;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * 进程
 * Class ModelHasFlow
 * @package app\common\models\flow
 * @property Flow flow
 * @property string state
 * @property int id
 * @property int model_id
 * @property int is_pending
 * @property string name
 * @property string code
 * @property Collection status
 * @property string model_type
 * @property string state_name
 * @property string status_name
 */
class Process extends BaseModel
{
    use HasProcessTrait, SoftDeletes, CanPendingTrait,BelongsStatusTrait;
    public $table = 'yz_process';

    protected $guarded = ['id'];
    protected $dates = ['created_at', 'updated_at'];
    protected $appends = ['name', 'status_name'];
    protected $hidden = ['flow', 'model_type'];
    const STATUS_PROCESSING = 'processing';
    const STATUS_COMPLETED = 'completed';
    const STATUS_CANCELED = 'canceled';

    /**
     * 进程的主体
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function model()
    {
        return $this->belongsTo($this->model_type, 'model_id');
    }

    /**
     * 所属流程类型
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function flow()
    {
        return $this->belongsTo(Flow::class);
    }

    public function member()
    {
        return $this->belongsTo(Member::class, 'uid');
    }

    /**
     * 初始化状态
     * @throws \Exception
     */
    public function initStatus()
    {
        // 流程的第一个情况
        $firstState = $this->flow->states->first();


        $this->setStatus($firstState);
    }

    /**
     * 进入下一个状态
     * @throws \Exception
     */
    public function toNextStatus()
    {
        // 流程的下一个情况
        $nextState = $this->flow->getNextState($this->currentStatus()->state);

        // 根据情况生成新状态
        $this->setStatus($nextState);
    }

    /**
     * @throws AppException
     */
    private function operationValidate(){
        // todo 是否可以考虑继续提取一个操作类
        if (isset($this->state) && $this->state != self::STATUS_PROCESSING) {
            throw new AppException("{$this->name}状态为{$this->state_name},无法继续操作");
        }

        if ($this->isPending() == true) {
            throw new AppException("{$this->name}已挂起,无法继续操作");
        }
    }
    /**
     * @param State $state
     * @throws AppException
     */
    private function setStatus(State $state)
    {
        $this->operationValidate();
        // 删除旧状态
        $this->status()->delete();
        if ($state->is($this->flow->getFinalState())) {
            // 流程执行完
            $this->state = self::STATUS_COMPLETED;
            $this->save();
        }
        $this->createStatus($state);
    }

    /**
     * @throws \Exception
     */
    public function toCloseState()
    {
        $closeState = $this->flow->getCloseState();
        $this->setStatus($closeState);

    }

    /**
     * @throws \Exception
     */
    public function toCancelState()
    {
        $cancelState = $this->flow->getCancelState();
        $this->setStatus($cancelState);

    }

    /**
     * @return string
     */
    public function getNameAttribute()
    {
        return $this->flow->name;
    }

    /**
     * @return string
     */

    public function getStateNameAttribute()
    {
        return [
            self::STATUS_PROCESSING => '处理中',
            self::STATUS_COMPLETED => '已完成',
            self::STATUS_CANCELED => '已取消',
        ][$this->state];
    }

    public function getStatusNameAttribute()
    {

        return $this->currentStatus()->state->name;
    }
    public function isPending(){
        return $this->is_pending;
    }
    public function getCodeAttribute(){
        return $this->flow->code;
    }
//    public function AfterCompleted(Closure $callback)
//    {
//
//
//    }
//    private function createCallback(Closure $callback){
//        if ($callback instanceof Closure) {
//            $callback = (new Serializer())->serialize($callback);
//        }
//        Callback::create(['key'=>'process.completed.','code'=>$callback]);
//    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //static::observe(new ProcessObserver());

    }
}
