<?php
/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2017/7/25
 * Time: 下午7:33
 */

namespace app\frontend\models\order;

use app\common\models\VirtualCoin;
use app\frontend\modules\order\models\PreGeneratedOrder;

abstract class PreOrderDeduction extends \app\common\models\order\OrderDeduction
{
    public $order;

    public function setOrder(PreGeneratedOrder $order)
    {
        $this->order = $order;
        $this->_init();
    }

    private function _init()
    {
        $this->uid = $this->order->uid;
        $this->order->orderDeductions->push($this);
        $this->coin = $this->getUsablePoint()->getCoin();

        $this->amount = $this->getUsablePoint()->getMoney();

        $this->name = $this->getName();
        $this->code = $this->getCode();

    }

    /**
     * @return VirtualCoin
     */
    abstract public function getUsablePoint();

    abstract public function getCode();

    abstract public function getName();



    public function isChecked()
    {
        return $this->isChecked();
    }

    public function save(array $options = [])
    {
        if (!$this->isChecked()) {
            // todo 应该返回什么
            return true;
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}