<?php
/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2017/7/25
 * Time: 下午7:10
 */

namespace app\frontend\models\order;

use app\frontend\modules\order\models\PreGeneratedOrder;

class PreOrderDiscount extends \app\common\models\order\OrderDiscount
{
    public $order;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->setRelation('orderDeduction', $this->newCollection());
        $this->setRelation('orderCoupon', $this->newCollection());
    }

    public function setOrder(PreGeneratedOrder $order)
    {
        $this->order = $order;
        $this->uid = $order->uid;
        $order->setRelation('orderDiscount', $this);
    }

    public function getPreAttributes()
    {
        $attributes = [
            'deduction_amount' => $this->getDeductionAmount(),
            'coupon_amount' => $this->getDeductionAmount(),
        ];
        $attributes = array_merge($this->getAttributes(), $attributes);
        return $attributes;
    }

    public function toArray()
    {
        $this->setRawAttributes($this->getPreAttributes());
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public function save(array $options = [])
    {
        $this->setRawAttributes($this->getPreAttributes());
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    //todo 累加所有抵扣金额
    public function getDeductionAmount()
    {
        return 0;
    }

    //todo 累加优惠券金额
    public function getCouponAmount()
    {
        return 0;
    }

    //public function get
}