<?php
global $_W;
$sql = "
drop table if exists " . tablename('yz_adv') . " ;
drop table if exists " . tablename('yz_carrier') . " ;
drop table if exists " . tablename('yz_category') . " ;
drop table if exists " . tablename('yz_commission_apply') . " ;
drop table if exists " . tablename('yz_commission_clickcount') . " ;
drop table if exists " . tablename('yz_commission_level') . " ;
drop table if exists " . tablename('yz_commission_log') . " ;
drop table if exists " . tablename('yz_commission_shop') . " ;
drop table if exists " . tablename('yz_designer') . " ;
drop table if exists " . tablename('yz_dispatch') . " ;
drop table if exists " . tablename('yz_express') . " ;
drop table if exists " . tablename('yz_feedback') . " ;
drop table if exists " . tablename('yz_goods') . "; 
drop table if exists " . tablename('yz_goods_comment') . " ;
drop table if exists " . tablename('yz_goods_option') . " ;
drop table if exists " . tablename('yz_goods_param') . " ;
drop table if exists " . tablename('yz_goods_spec') . " ;
drop table if exists " . tablename('yz_goods_spec_item') . " ;
drop table if exists " . tablename('yz_member') . " ;
drop table if exists " . tablename('yz_member_address') . " ;
drop table if exists " . tablename('yz_member_cart') . " ;
drop table if exists " . tablename('yz_member_favorite') . " ;
drop table if exists " . tablename('yz_member_group') . " ;
drop table if exists " . tablename('yz_member_history') . " ;
drop table if exists " . tablename('yz_member_level') . " ;
drop table if exists " . tablename('yz_member_log') . " ;
drop table if exists " . tablename('yz_member_message_template') . " ;
drop table if exists " . tablename('yz_notice') . " ;
drop table if exists " . tablename('yz_order') . " ;
drop table if exists " . tablename('yz_order_comment') . " ;
drop table if exists " . tablename('yz_order_goods') . " ;
drop table if exists " . tablename('yz_order_refund') . " ;
drop table if exists " . tablename('yz_perm_log') . " ;
drop table if exists " . tablename('yz_perm_plugin') . "; 
drop table if exists " . tablename('yz_perm_role') . " ;
drop table if exists " . tablename('yz_perm_user') . " ;
drop table if exists " . tablename('yz_plugin') . " ;
drop table if exists " . tablename('yz_poster') . " ;
drop table if exists " . tablename('yz_poster_log') . " ;
drop table if exists " . tablename('yz_poster_qr') . " ;
drop table if exists " . tablename('yz_poster_scan') . " ;
drop table if exists " . tablename('yz_saler') . " ;
drop table if exists " . tablename('yz_store') . " ;
drop table if exists " . tablename('yz_sysset') . " ;
drop table if exists " . tablename('yz_creditshop_adv') . " ;
drop table if exists " . tablename('yz_creditshop_category') . " ;
drop table if exists " . tablename('yz_creditshop_goods') . " ;
drop table if exists " . tablename('yz_creditshop_log') . " ;
drop table if exists " . tablename('yz_virtual_category') . " ;
drop table if exists " . tablename('yz_virtual_data') . " ;
drop table if exists " . tablename('yz_virtual_type') . " ;
drop table if exists " . tablename('yz_designer_menu') . " ;
drop table if exists " . tablename('yz_article') . " ;
drop table if exists " . tablename('yz_article_category') . " ;
drop table if exists " . tablename('yz_article_log') . " ;
drop table if exists " . tablename('yz_article_report') . " ;
drop table if exists " . tablename('yz_article_share') . " ;
drop table if exists " . tablename('yz_article_sys') . " ;
drop table if exists " . tablename('yz_postera_log') . " ;
drop table if exists " . tablename('yz_postera_qr') . " ;
drop table if exists " . tablename('yz_coupon') . " ;
drop table if exists " . tablename('yz_coupon_category') . " ;
drop table if exists " . tablename('yz_coupon_data') . " ;
drop table if exists " . tablename('yz_coupon_guess') . " ;
drop table if exists " . tablename('yz_coupon_log') . " ;
";
pdo_query($sql);
