<?php
/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2017/7/25
 * Time: 下午7:10
 */

namespace app\frontend\models\orderGoods;

use app\common\models\VirtualCoin;
use app\frontend\models\GoodsDeduction;
use app\frontend\models\OrderGoods;
use Yunshop\Love\Frontend\Models\PreLoveDeduction;

class PreOrderGoodsDeduction extends \app\common\models\orderGoods\OrderGoodsDeduction
{
    /**
     * @var OrderGoods
     */
    public $orderGoods;

    /**
     * @var GoodsDeduction
     */
    public $goodsDeduction;
    /**
     * @var PreLoveDeduction
     */
    private $deduction;
    private $usablePoint;
    private $orderDeduction;

    public function __construct(array $attributes = [], $orderGoods, $orderDeduction)
    {
        parent::__construct($attributes);
        $this->setOrderDeduction($orderDeduction);

        $this->setOrderGoods($orderGoods);

        $this->setGoodsDeduction();

        $this->code = $this->getCode();

        $this->name = $this->getName();
    }

    // todo 写活

    private function getCode()
    {
        return 'love';
    }

    /**
     * @return PreLoveDeduction
     */
    private function getDeduction()
    {

        return $this->deduction ?: $this->deduction = $this->orderDeduction->getDeduction();
    }

    private function getName()
    {
        return $this->getDeduction()->name;
    }

    private function newCoin()
    {
        return new VirtualCoin();

    }

    private function setOrderGoods($orderGoods)
    {
        $this->orderGoods = $orderGoods;
        $this->uid = $orderGoods->uid;
        $orderGoods->setRelation('loveOrderGoods', $this);
    }
    private function setGoodsDeduction(){
        // todo
        dd(get_class($this->getDeduction()));
        exit;

        //$this->goodsDeduction = $this->getDeduction()->getGoodsDeduction();
        $this->goodsDeduction = $goodsDeduction->whereGoodsId($orderGoods->goods_id)->first();

    }
    private function setOrderDeduction($orderDeduction)
    {
        $this->orderDeduction = $orderDeduction;
    }

    /**
     * 订单抵扣模型
     * @return mixed
     * @throws \Exception
     */
    private function getOrderDeduction()
    {
        if (!isset($this->orderDeduction)) {
            throw new \Exception('未设置OrderDeduction');
        }
        return $this->orderDeduction;
    }

    /**
     * 获取订单商品可用的爱心值
     * @return VirtualCoin
     */
    public function getUsablePoint()
    {
        if (isset($this->usablePoint)) {
            return $this->usablePoint;
        }
        if (!isset($this->goodsDeduction)) {
            // 购买商品不存在抵扣记录
            return $this->newCoin();
        }
        $loveCoin = $this->goodsDeduction->getUsableLoveCoin($this->orderGoods->goods_price);

        return $this->usablePoint = $loveCoin;
    }


    /**
     * 获取订单商品实际使用的爱心值,是不是考虑已使用的和可使用的分成两个类
     * @return VirtualCoin
     */
    private function getUsedPoint()
    {
        // 订单商品抵扣金额 * (订单商品集合抵扣金额/订单实际抵扣金额)
        $amount = $this->getUsablePoint()->getMoney() * ($this->getOrderDeduction()->getOrderGoodsCollectionDeduction()->getUsablePoint()->getMoney() / $this->getOrderDeduction()->getUsablePoint()->getMoney());
        return $this->newCoin()->setMoney($amount);
    }

    public function save(array $options = [])
    {
        $this->usable_amount = $this->getUsablePoint()->getMoney();
        $this->usable_coin = $this->getUsablePoint()->getCoin();
        $this->used_amount = $this->getUsedPoint()->getMoney();
        $this->used_coin = $this->getUsedPoint()->getCoin();

        return parent::save($options); // TODO: Change the autogenerated stub
    }
}