<?php
/**
 * Created by PhpStorm.
 * User: luckystar_D
 * Date: 2017/3/4
 * Time: 上午11:24
 */

namespace app\backend\modules\goods\models;


class Area  extends \app\common\models\Area
{
    /**
     * 获取地区信息
     * @return mixed
     */
    public static function getAreaList()
    {
        return parent::getAreaList(); // TODO: Change the autogenerated stub
    }

    public static function getProvinces($parentId)
    {
        return parent::getProvinces($parentId); // TODO: Change the autogenerated stub
    }

    public static function getCitysByProvince($parentId)
    {
        return parent::getCitysByProvince($parentId); // TODO: Change the autogenerated stub
    }

    public static function getAreasByCity($parentId)
    {
        return parent::getAreasByCity($parentId); // TODO: Change the autogenerated stub
    }
}