<?php
/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2018/6/14
 * Time: 下午5:31
 */

namespace app\common\models\flow;

use app\common\models\Flow;
use Illuminate\Database\Eloquent\Builder;

class AuditFlow extends Flow
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(function (Builder $builder) {
            $builder->where('code',self::class);
        });
    }
}