<?php
/**
 * Created by PhpStorm.
 * User: yunzhong
 * Date: 2018/10/15
 * Time: 16:32
 */

namespace app\backend\modules\charts\models;


use Yunshop\Supplier\common\models\SupplierWithdraw;
use Yunshop\Supplier\supplier\models\SupplierOrder;

class Supplier extends \Yunshop\Supplier\common\models\Supplier
{

    public function hasManySupplierOrder()
    {
        return $this->hasMany(SupplierOrder::class, 'supplier_id', 'id'); // TODO: Change the autogenerated stub
    }

    public function hasManySupplierOrderCount()
    {
        return $this->hasMany(SupplierOrder::class, 'supplier_id', 'id'); // TODO: Change the autogenerated stub
    }

    public function hasManySupplierWithdraw()
    {
        return $this->hasMany(SupplierWithdraw::class, 'supplier_id', 'id'); // TODO: Change the autogenerated stub
    }
}