<?php
/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2017/4/11
 * Time: 上午10:20
 */

namespace app\frontend\modules\order\controllers;

use app\frontend\modules\member\services\MemberCartService;
use Request;

class GoodsBuyController extends PreGeneratedController
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
    protected function getShopMemberCarts(){
        return MemberCartService::filterShopMemberCart($this->getMemberCarts());
    }
    protected function getMemberCarts()
    {
        $goods_params = [
            'goods_id' => Request::query('goods_id'),
            'total' => Request::query('total'),
            'option_id' => Request::query('option_id'),
        ];
        $result = collect();
        return $result->push(MemberCartService::newMemberCart($goods_params));
    }
}