<?php
/**
 * Created by PhpStorm.
 * User: shenyang
 * Date: 2017/2/28
 * Time: 下午1:44
 */

namespace app\frontend\modules\goods\model;


use app\common\models\Goods;
use app\common\ServiceModel\ServiceModel;

class PreGeneratedOrderGoods extends ServiceModel
{
    private $total;
    private $order_model;
    private $goods_model;

    public function __construct()
    {
    }
    public function setTotal($total){
        $this->total = $total;
    }
    public function setOrderModel($order_model){
        $this->order_model = $order_model;
    }
    public function setGoodsModel($goods_model){
        $this->goods_model = $goods_model;
    }
    public function generate()
    {
        $this->order_model->getOrderId();
        $data = array(
            'shop_id' => $this->order_model->getShopModel()->getShopId(),
            'order_id' => $this->order_model->getOrderId(),
            'goods_id' => $this->goods_model->getGoodsId(),
            'goods_sn' => $this->goods_model->getGoodsSn(),
            'member_id' => $this->order_model->getMemberModel()->getMemberId(),
            'price' => $this->getPrice(),
            'total' => $this->getTotal(),
            'price' => $this->getPrice(),
        );
        return Goods::insertGetId($data);
    }
    public function __get($name)
    {
        if($this->goods_model->$name !== null){
            return $this->goods_model->$name;
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }
}